### ISSUE TITLE
402: Payment required DEPLOYMENT_BLOCKED for one of the showcase apps

### ISSUE THREAD

**Issue by lennartstolz** [zeit/awesome-zeit#88]
Hey ho! 👍 

First of all:

I just listened an episode of the "Software Engineering Daily" podcast talking about your products.
Sounds super nice! 👏 

When checking this repo I realized that one of the showcase apps is actually bringing the mentioned `402` status page.

It's the following one: https://color.now.sh/

Best,
Lennart

**Comment by timothyis** [comment]
Thanks for spotting that @lennartstolz! I've removed the entry for now and will contact the author to see what we can do! 🙏
